[package]
name = "nub"
version = "2019.11.19"
authors = ["Magicloud <1886157+Magicloud@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
panic = 'abort'
